name: ${name}
version: '${version}'
main: fr.traqueur.morebees.MoreBees
api-version: '1.21'
authors: [Traqueur_]
soft-depend:
  - ItemsAdder
  - ModelEngine
  - Oraxen
  - Nexo
paper-skip-libraries: true
paper-plugin-loader: fr.traqueur.morebees.MoreBeesLoader
libraries: ${libraries}
